# Generated by Django 3.0.4 on 2020-04-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200415_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
